id: A10CC6F5C
title: Acala Sādhana
type: translation
pechas:
- I48C49648
- IF7E98A77
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:11:38.664631
  last_modified_at: 2023-01-04 13:11:38.664641
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I48C49648/A2AD: DC95
  IF7E98A77/FDD2: DC95
